### PR TITLE
Add support for pkg-config in qatlib

### PR DESCRIPTION
**Pull request by adenilsoncavalcanti**
Allows easier integration with other apps/libs by offering support for pkg-config tool.

### CODE REVIEW

**Review by fionatrahe — APPROVED** [review]
THanks. we intend to pull this into a future release.

**Review by fionatrahe — COMMENTED** [review]
approved too soon, we'd like to rework this before adding

**Comment by adenilsoncavalcanti** [comment]
@fionatrahe thanks for the feedback, I really appreciate it.

What would you like to rework on the current patch so that it could be merged?

**Comment by fionatrahe** [comment]
@adenilsoncavalcanti qatlib also has a dependency on openssl.

**Comment by gcabiddu** [comment]
Thanks @adenilsoncavalcanti. This will be included as part of the next release. Closing.

**Pull request closed without merging**
